### PR TITLE
chore: migrate to helm-charts

### PR DESCRIPTION
**Pull request by Wielewout**

### CODE REVIEW

**Review by ben-foxmoore — APPROVED** [review]
Will the Helm index automatically be updated, or do we need to handle that as a separate PR to `gh-pages` branch?

**Comment by Wielewout** [comment]
> Will the Helm index automatically be updated, or do we need to handle that as a separate PR to `gh-pages` branch?

I'm doing that now, but for some reason it still works for me to pull charts?

**Comment by Wielewout** [comment]
Looks like github is redirecting us for now, I'll update the index file directly on `gh-pages`.

**Comment by ben-foxmoore** [comment]
>We keep redirects for moved and renamed repos indefinitely, but new repos take priority over redirects. That means if a new repo is created at an old location, the redirects will break in favor of displaying the new repo, for as long as that new repo exists.

[source](https://github.com/orgs/community/discussions/22669#discussioncomment-3237667)

This is quite good for us - links to `helm-charts-ng` are still working, so essentially both that and `helm-charts` now point here.

**Comment by Wielewout** [comment]
Forgot to update all subchart dependenciess (config-api, ...). A new PR will come up...

**Pull request merged**
