### PR TITLE
feat: added snssai pm counters

### PR DESCRIPTION
**Pull request by colinmhoward**

### CODE REVIEW

**Comment by ben-foxmoore** [comment]
@colinmhoward the test is failing as you need to update the Chart.lock file (I thought it was probably easier to wait for it to fail to try and explain 😅). To resolve this, you just need to do a `helm dependency update` in the `drax` chart folder. This will probably give you an error message about repos, which can be resolved by running the [bin/add-repos](https://github.com/accelleran/helm-charts-ng/blob/main/bin/add-repos) script first.

**Comment by ben-foxmoore** [comment]
Also, for the commit message, `!` indicates a breaking change - is that the case here?

**Comment by colinmhoward** [comment]
OK thanks – that seemed to work. There were no errors generated.

From: Ben Fox-Moore ***@***.***>
Date: Monday, 5 February 2024 at 10:39
To: accelleran/helm-charts-ng ***@***.***>
Cc: Colin Howard ***@***.***>, Mention ***@***.***>
Subject: Re: [accelleran/helm-charts-ng] feat!: added snssai pm counters (PR #63)

@colinmhoward<https://github.com/colinmhoward> the test is failing as you need to update the Chart.lock file (I thought it was probably easier to wait for it to fail to try and explain 😅). To resolve this, you just need to do a helm dependency update in the drax chart folder. This will probably give you an error message about repos, which can be resolved by running the bin/add-repos<https://github.com/accelleran/helm-charts-ng/blob/main/bin/add-repos> script.

**Comment by colinmhoward** [comment]
Ah ok – no it is not a breaking change. I will just use feat: in the next commit. Do I need to do anything to remove the feat! Commit message?
From: Ben Fox-Moore ***@***.***>
Date: Monday, 5 February 2024 at 10:40
To: accelleran/helm-charts-ng ***@***.***>
Cc: Colin Howard ***@***.***>, Mention ***@***.***>
Subject: Re: [accelleran/helm-charts-ng] feat!: added snssai pm counters (PR #63)

Also, for the commit message, ! indicates a breaking change - is that the case here?

**Comment by ben-foxmoore** [comment]
You could have just changed the message of your previous commit (`git commit --amend`), and then force pushed the branch. Now with the extra commit on top, you'd need to interactive rebase. @Wielewout any idea what happens if we "Squash and merge" here on Github? Do we need to just change the PR title and it will use that for the merge commit?

**Comment by Wielewout** [comment]
Normally github will propose the commit message that you merge. I think by default it will use the title of the PR, but also make sure that all the commits that are included in the PR are left out of the body then (so probably it's best to override history and rename the commit + rename PR title to prevent mistakes there)

**Comment by colinmhoward** [comment]
I think I have resolved these issues now. Thanks for the tips!!

From: Wout Van De Wiel ***@***.***>
Date: Monday, 5 February 2024 at 10:54
To: accelleran/helm-charts-ng ***@***.***>
Cc: Colin Howard ***@***.***>, Mention ***@***.***>
Subject: Re: [accelleran/helm-charts-ng] feat!: added snssai pm counters (PR #63)

Normally github will propose the commit message that you merge. I think by default it will use the title of the PR, but also make sure that all the commits that are included in the PR are left out of the body then (so probably it's best to override history and rename the commit + rename PR title to prevent mistakes there)

**Review by Wielewout — APPROVED** [review]
Looks good!

Small note: it would be better to always add the proper type of commit. Now there is one without it. When we wouldn't squash merge there would be one ignored etc.

The history would have looked more like this then:

* feat: add snssai pm counters
* fix: fix drax chart dependencies

Though as long as we squash merge it will be fine :smile:

**Comment by colinmhoward** [comment]
OK thanks!

From: Wout Van De Wiel ***@***.***>
Date: Monday, 5 February 2024 at 11:23
To: accelleran/helm-charts-ng ***@***.***>
Cc: Colin Howard ***@***.***>, Mention ***@***.***>
Subject: Re: [accelleran/helm-charts-ng] feat: added snssai pm counters (PR #63)

@Wielewout approved this pull request.

Looks good!

Small note: it would be better to always add the proper type of commit. Now there is one without it. When we wouldn't squash merge there would be one ignored etc.

The history would have looked more like this then:

  *   feat: add snssai pm counters
  *   fix: fix drax chart dependencies

Though as long as we squash merge it will be fine 😄

**Pull request merged**
