### PR TITLE
fix!: bump default cu version to 9

### PR DESCRIPTION
**Pull request by dimgogos**

### CODE REVIEW

**Review by Wielewout — COMMENTED** [review]
I guess we should indicate it as breaking (i.e. `fix!`)?

**Comment by dimgogos** [comment]
> I guess we should indicate it as breaking (i.e. `fix!`)?

Hmm, the CU application itself contains breaking changes and the config api will be bumped to a new major version. I wonder if it 's breaking in terms of the helm charts/service orchestrator...

**Comment by Wielewout** [comment]
Changing a default is (I think?) always a breaking change.

In this case we're changing the behaviour from a dRAX perspective as the CU that we now will deploy by default results in breaking changes (as also indicated by the major version bump). So anything that relies on broken functionality in the CU should also have an indication of a breaking change here through dRAX deploying it.

**Comment by dimgogos** [comment]
> Changing a default is (I think?) always a breaking change.
> 
> In this case we're changing the behaviour from a dRAX perspective as the CU that we now will deploy by default results in breaking changes (as also indicated by the major version bump). So anything that relies on broken functionality in the CU should also have an indication of a breaking change here through dRAX deploying it.

Ok fair point

**Review by Wielewout — APPROVED** [review]

**Pull request merged**
