### PR TITLE
Enable automerging for Renovate changes other than Major

### PR DESCRIPTION
**Pull request by ben-foxmoore**

### CODE REVIEW

**Comment by ben-foxmoore** [comment]
Wondering if this is a good change - I actually intended it for the Github Actions originally because we're less likely to care about the specific version of that...

**Review by Wielewout — COMMENTED** [review]
I don't immediately see an issue with the helm charts also being updated with minor and patch versions... Even major versions should be caught by the tests in the CI (ideally).

Do we even need a plugin? https://docs.renovatebot.com/key-concepts/automerge/

```json
{
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
}
```

**Comment by ben-foxmoore** [comment]
The change isn't a plugin, it's just a "preset" - essentially a bundle of configuration ready to be used (just like the semantic commits preset).

It's essentially what you've got there actually. You can see the details here: https://docs.renovatebot.com/presets-default/#automergeminor

I think this just has the advantage that if something changes in Renovate, the preset should automatically be updated.

**Review by Wielewout — APPROVED** [review]

**Comment by ben-foxmoore** [comment]
Worst case - if we find the automerging of chart updating annoying, we can always restrict it later.

**Pull request merged**
