### PR TITLE
feat!: update grafana dash to influxdb2

### PR DESCRIPTION
**Pull request by dimgogos**
This PR updates the grafana dashboards to use influxdb2 for showing dRAX metrics. It also removes the InfluxDB 1.X from our system together with Vector

### CODE REVIEW

**Review by adugast — APPROVED** [review]
Nice change,

For my information, I see that influxdb had a backup configuration with the nodeSelector, do we have a similar feature for influxdb2?

**Comment by dimgogos** [comment]
> Nice change,
> 
> For my information, I see that influxdb had a backup configuration with the nodeSelector, do we have a similar feature for influxdb2?

You mean in the values-node-selector.yaml? There is a section for influxdb2 as well

**Comment by adugast** [comment]
Yes, in the values-node-selector.yaml,

Infludb has:
`influxdb:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
  backup:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
`

and Influxdb2:
`influxdb2:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
`
So it misses the backup section? :thinking:

**Comment by dimgogos** [comment]
> Yes, in the values-node-selector.yaml,
> 
> Infludb has: `influxdb: nodeSelector: drax.accelleran.com/schedule: "true" backup: nodeSelector: drax.accelleran.com/schedule: "true" `
> 
> and Influxdb2: `influxdb2: nodeSelector: drax.accelleran.com/schedule: "true" ` So it misses the backup section? 🤔

I can see here [https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml](url) that we just need the nodeSelector. I guess there was a different config for influxdB 1.X

**Pull request merged**
